sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - autoconf
    - bison
    - flex
    - libssl-dev
    - libevent-dev
    - clang
script:
  - autoconf && autoheader
  - ./configure --enable-checking --disable-flto
  - make
  - make cutest && ./cutest
  - (cd tpkg; ./mini_tpkg.sh exe clang-analysis.tpkg ; if grep -e "warning:" -e "error:" result.clang-analysis ; then exit 1; else exit 0; fi)
